### ISSUE TITLE
Time out on local IP conection..

### ISSUE THREAD

**Issue by fjs21** [fjs21/homebridge-kumo#17]
I've started seeing this error in my status using Kumo plugin 1.2.8. Also I do not see a notice to update to 1.3.8.

[2/10/2021, 10:07:53 PM] [Kumo] Kumo API: bad response from queryDevice_Direct - { _api_error: 'device_authentication_error' }
[2/10/2021, 10:07:53 PM] [Kumo] queryDevice_Direct failed.
[2/10/2021, 11:07:57 PM] [Kumo] queryDevice_Direct error: Time out on local IP connection..
[2/10/2021, 11:07:57 PM] [Kumo] queryDevice_Direct failed.
[2/10/2021, 11:12:33 PM] [Kumo] queryDevice_Direct error: Time out on local IP connection..
[2/10/2021, 11:12:33 PM] [Kumo] queryDevice_Direct failed.
[2/10/2021, 11:12:36 PM] [AugustLocks] [August Front Door] State was successfully set to lock
[2/10/2021, 11:12:46 PM] [Kumo] queryDevice_Direct error: FetchError: request to http://192.168.1.213/api?m=549907a7adeb381dc401177841dd70b745bb8fba76b91ef4cba292cb1df3906f failed, reason: connect EHOSTUNREACH 192.168.1.213:80
    at ClientRequest.<anonymous> (/usr/local/lib/node_modules/homebridge-kumo/node_modules/node-fetch/lib/index.js:1461:11)
    at ClientRequest.emit (events.js:315:20)
    at Socket.socketErrorListener (_http_client.js:426:9)
    at Socket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  type: 'system',
  errno: 'EHOSTUNREACH',
  code: 'EHOSTUNREACH'
}.
[2/10/2021, 11:12:46 PM] [Kumo] queryDevice_Direct failed.
[2/10/2021, 11:13:00 PM] [Kumo] queryDevice_Direct error: FetchError: request to http://192.168.1.213/api?m=549907a7adeb381dc401177841dd70b745bb8fba76b91ef4cba292cb1df3906f failed, reason: connect EHOSTUNREACH 192.168.1.213:80
    at ClientRequest.<anonymous> (/usr/local/lib/node_modules/homebridge-kumo/node_modules/node-fetch/lib/index.js:1461:11)
    at ClientRequest.emit (events.js:315:20)
    at Socket.socketErrorListener (_http_client.js:426:9)
    at Socket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  type: 'system',
  errno: 'EHOSTUNREACH',
  code: 'EHOSTUNREACH'
}.
[2/10/2021, 11:13:00 PM] [Kumo] queryDevice_Direct failed.
[2/11/2021, 1:07:57 AM] [Kumo] queryDevice_Direct error: Time out on local IP connection..
[2/11/2021, 1:07:57 AM] [Kumo] queryDevice_Direct failed.

_Originally posted by @PeterJ73 in https://github.com/fjs21/homebridge-kumo/issues/11#issuecomment-777805605_

**Comment by fjs21** [comment]
Hi @PeterJ73,

I think this might be due to a change in IP address for your device. You could unchecking "direct" connection in the setup to see if it resolves as the cloud based connection doesn't use the local IP connection. It's a bit slower but more resilient to changes such as these.

Alternatively, you can modify your device's IP to restore it to the original IP address. I have done this with my devices by setting my router to give the same IP address (akin to a static IP). 

Eventually, though I'm not sure how long, the Kumo cloud will obtain the new IP address settings and things will start working again. I did try for some period to see if I could manually get the IP address via the device's MAC but was unsuccessful.  

Thanks for your support. 

Cheers,
Fraser

**Comment by derk1127** [comment]
I think I am seeing the same error in my kumo system. Here's the error log I got:

[2/16/2021, 11:49:27 AM] [Kumo] queryDevice_Direct error: FetchError: request to http://192.168.1.51/api?m=89adb93c1a08ad059390ef1ed79c7e0f87aba737bae81a872450177a4ee88811 failed, reason: connect EHOSTUNREACH 192.168.1.51:80
    at ClientRequest.<anonymous> (/usr/lib/node_modules/homebridge-kumo/node_modules/node-fetch/lib/index.js:1461:11)
    at ClientRequest.emit (events.js:315:20)
    at Socket.socketErrorListener (_http_client.js:426:9)
    at Socket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  type: 'system',
  errno: 'EHOSTUNREACH',
  code: 'EHOSTUNREACH'
}.
[2/16/2021, 11:49:27 AM] [Kumo] queryDevice_Direct failed.

**Comment by fjs21** [comment]
This still looks like an IP resolution error. The Kumo plugin thinks the device is assigned 192.168.1.51 by your WiFi router. First thing would be to double check that your Kumo device is indeed assigned 192.168.1.51. If not, the easiest thing would be to have the WiFi router assign the Kumo unit to that address and keep that address fixed going forward. If your router is unable to assign static addresses, then I recommend that you switch away from direct connections by unchecking the box in the plugin config page. This problem will crop up every time your router assigns a new IP address and there is no easy automated fix (that I could find) that would solve this without moving to a static IP.
