### ISSUE TITLE
queryDevice_Direct error

### ISSUE THREAD

**Issue by VeniceNerd** [fjs21/homebridge-kumo#22]
Hey,

I'm getting a weird error in my logs:

[5/6/2021, 10:58:16 AM] [homebridge-kumo] This plugin generated a warning from the characteristic 'Cooling Threshold Temperature': characteristic value expected valid finite number and received "undefined" (undefined). See https://git.io/JtMGR for more info.
[5/6/2021, 10:58:16 AM] [homebridge-kumo] This plugin generated a warning from the characteristic 'Current Temperature': characteristic was supplied illegal value: null! Home App will reject null for Apple defined characteristics. See https://git.io/JtMGR for more info.
[5/6/2021, 10:58:16 AM] [homebridge-kumo] This plugin generated a warning from the characteristic 'Rotation Speed': characteristic was supplied illegal value: number -20 exceeded minimum of 0. See https://git.io/JtMGR for more info.
[5/6/2021, 10:58:16 AM] [homebridge-kumo] This plugin generated a warning from the characteristic 'Current Heating Cooling State': characteristic value expected valid finite number and received "undefined" (undefined). See https://git.io/JtMGR for more info.
[5/6/2021, 10:58:16 AM] [homebridge-kumo] This plugin generated a warning from the characteristic 'Cooling Threshold Temperature': characteristic value expected valid finite number and received "undefined" (undefined). See https://git.io/JtMGR for more info.
[5/6/2021, 10:58:16 AM] [homebridge-kumo] This plugin generated a warning from the characteristic 'Current Temperature': characteristic was supplied illegal value: null! Home App will reject null for Apple defined characteristics. See https://git.io/JtMGR for more info.
[5/6/2021, 10:58:16 AM] [homebridge-kumo] This plugin generated a warning from the characteristic 'Rotation Speed': characteristic was supplied illegal value: number -20 exceeded minimum of 0. See https://git.io/JtMGR for more info.
[5/6/2021, 10:58:16 AM] [homebridge-kumo] This plugin generated a warning from the characteristic 'Active': characteristic value expected valid finite number and received "undefined" (undefined). See https://git.io/JtMGR for more info.
[5/6/2021, 10:58:16 AM] [homebridge-kumo] This plugin generated a warning from the characteristic 'Cooling Threshold Temperature': characteristic value expected valid finite number and received "undefined" (undefined). See https://git.io/JtMGR for more info.
[5/6/2021, 10:58:16 AM] [homebridge-kumo] This plugin generated a warning from the characteristic 'Current Temperature': characteristic was supplied illegal value: null! Home App will reject null for Apple defined characteristics. See https://git.io/JtMGR for more info.
[5/6/2021, 10:58:16 AM] [homebridge-kumo] This plugin generated a warning from the characteristic 'Rotation Speed': characteristic was supplied illegal value: number -20 exceeded minimum of 0. See https://git.io/JtMGR for more info.
[5/6/2021, 10:58:16 AM] [homebridge-kumo] This plugin generated a warning from the characteristic 'Target Temperature': characteristic value expected valid finite number and received "undefined" (undefined). See https://git.io/JtMGR for more info.
[5/6/2021, 10:58:16 AM] [homebridge-kumo] This plugin generated a warning from the characteristic 'Cooling Threshold Temperature': characteristic value expected valid finite number and received "undefined" (undefined). See https://git.io/JtMGR for more info.
[5/6/2021, 10:58:16 AM] [homebridge-kumo] This plugin generated a warning from the characteristic 'Current Temperature': characteristic was supplied illegal value: null! Home App will reject null for Apple defined characteristics. See https://git.io/JtMGR for more info.
[5/6/2021, 10:58:16 AM] [homebridge-kumo] This plugin generated a warning from the characteristic 'Rotation Speed': characteristic was supplied illegal value: number -20 exceeded minimum of 0. See https://git.io/JtMGR for more info.
[5/6/2021, 10:58:16 AM] [homebridge-kumo] This plugin generated a warning from the characteristic 'Target Heating Cooling State': characteristic value expected valid finite number and received "undefined" (undefined). See https://git.io/JtMGR for more info.
[5/6/2021, 10:58:16 AM] [homebridge-kumo] This plugin generated a warning from the characteristic 'Cooling Threshold Temperature': characteristic value expected valid finite number and received "undefined" (undefined). See https://git.io/JtMGR for more info.
[5/6/2021, 10:58:16 AM] [homebridge-kumo] This plugin generated a warning from the characteristic 'Current Temperature': characteristic was supplied illegal value: null! Home App will reject null for Apple defined characteristics. See https://git.io/JtMGR for more info.
[5/6/2021, 10:58:16 AM] [homebridge-kumo] This plugin generated a warning from the characteristic 'Rotation Speed': characteristic was supplied illegal value: number -20 exceeded minimum of 0. See https://git.io/JtMGR for more info.
[5/6/2021, 10:58:16 AM] [homebridge-kumo] This plugin generated a warning from the characteristic 'Current Temperature': characteristic value expected valid finite number and received "undefined" (undefined). See https://git.io/JtMGR for more info.
[5/6/2021, 10:58:19 AM] [Kumo] queryDevice_Direct error: FetchError: request to http://10.0.1.91/api?m=72032007a6f8519e90357d67743f584db920530e2b316cb481a70dfb977fb69d failed, reason: connect EHOSTUNREACH 10.0.1.91:80
    at ClientRequest.<anonymous> (/homebridge/node_modules/homebridge-kumo/node_modules/node-fetch/lib/index.js:1461:11)
    at ClientRequest.emit (events.js:315:20)
    at Socket.socketErrorListener (_http_client.js:469:9)
    at Socket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  type: 'system',
  errno: 'EHOSTUNREACH',
  code: 'EHOSTUNREACH'
}.
[5/6/2021, 10:58:19 AM] [Kumo] queryDevice_Direct failed.

Any idea what that could be about?

Thanks!

Philipp

**Comment by fjs21** [comment]
The plugin is having a hard time reaching the your device at the IP address. This could be due to a temporary issue or can happen if your Kumo device has changed it's IP address. The important part is at the end. You could also try turning off Direct connection to see if you have a better experience.
