### ISSUE TITLE
Pulling incorrect IP's for direct connect.

### ISSUE THREAD

**Issue by cdafler** [fjs21/homebridge-kumo#36]
I have Manually assigned IP's for the Kumo cloud units in my home. the Home-bridge plugin keeps pulling the old IP's. I cannot find the location to flush those out.

**Comment by cdafler** [comment]
[9/12/2021, 2:05:37 PM] [Kumo] queryDevice_Direct error: FetchError: request to **http://10.10.1.163**/api?m=4abb3f0e6bbbda56695fa70a5913e31f23d20ce45b3166e375edea8081522f78 failed, reason: connect EHOSTUNREACH 10.10.1.163:80
    at ClientRequest.<anonymous> (/usr/lib/node_modules/homebridge-kumo/node_modules/node-fetch/lib/index.js:1461:11)
    at ClientRequest.emit (events.js:400:28)
    at Socket.socketErrorListener (_http_client.js:475:9)
    at Socket.emit (events.js:400:28)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  type: 'system',
  errno: 'EHOSTUNREACH',
  code: 'EHOSTUNREACH'

**Comment by fjs21** [comment]
Hi, yes this is an issue I have faced. I wasn't able to work out a suitable way to flush these out either but after a period (1 day?) it seems to resolve itself. You might be able to 'prompt' it by using the kumo app. In any case, you can restore functionality in the meantime by turning off "direct connection" as this will use the kumo cloud to connect. It is a little slower but works.

**Comment by eleventhaus** [comment]
Same issue. I set static IPs last night, but after reviewing the debug logs I see that the old IPs are being sent from Kumo Cloud. I'm guessing it takes a few days for the Kumo servers to update.
