### ISSUE TITLE
Latest plugin update killed my Kumo access through Homebridge

### ISSUE THREAD

**Issue by hansw1204** [fjs21/homebridge-kumo#55]
After installing the latest update, my accessories do not appear on Homebridge nor Homekit anymore. Reverting to previous version does not remedy the issue.
EDIT: reverting to .18 got my accessories back but had to install new child bridge

**Comment by fjs21** [comment]
Can you post your logs? There’s not much to go on here.

**Comment by FTI76** [comment]
It killed mine also - homebridge-kumo v1.8.21

[1/22/2022, 2:59:25 PM] ---
[1/22/2022, 2:59:25 PM] ====================
[1/22/2022, 2:59:25 PM] ERROR LOADING PLUGIN homebridge-kumo:
[1/22/2022, 2:59:25 PM] Error [ERR_REQUIRE_ESM]: require() of ES Module /usr/lib/node_modules/homebridge-kumo/node_modules/node-fetch/src/index.js from /usr/lib/node_modules/homebridge-kumo/node_modules/fetch-timeout/src/index.js not supported.
Instead change the require of /usr/lib/node_modules/homebridge-kumo/node_modules/node-fetch/src/index.js in /usr/lib/node_modules/homebridge-kumo/node_modules/fetch-timeout/src/index.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/usr/lib/node_modules/homebridge-kumo/node_modules/fetch-timeout/src/index.js:6:18)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge-kumo/dist/kumo-api.js:7:41)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge-kumo/dist/platform.js:4:20)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge-kumo/dist/index.js:3:20)
    at Plugin.load (/usr/lib/node_modules/homebridge/lib/plugin.js:135:108)
    at PluginManager.initializeInstalledPlugins (/usr/lib/node_modules/homebridge/lib/pluginManager.js:64:30)
    at async Server.start (/usr/lib/node_modules/homebridge/lib/server.js:106:9)
[1/22/2022, 2:59:25 PM] ====================

**Comment by fjs21** [comment]
Ok. I'm running Node.js Version 16.13.0, NPM 8.1.0, and Homebridge 1.4.0. Working fine here. I'll need to dig further.

**Comment by hansw1204** [comment]
Here is mine Looks identical)

 

[1/22/2022, 12:16:22 PM] ====================

[1/22/2022, 12:16:22 PM] ERROR LOADING PLUGIN homebridge-kumo:

[1/22/2022, 12:16:22 PM] Error [ERR_REQUIRE_ESM]: require() of ES Module /homebridge/node_modules/homebridge-kumo/node_modules/node-fetch/src/index.js from /homebridge/node_modules/homebridge-kumo/node_modules/fetch-timeout/src/index.js not supported.

Instead change the require of /homebridge/node_modules/homebridge-kumo/node_modules/node-fetch/src/index.js in /homebridge/node_modules/homebridge-kumo/node_modules/fetch-timeout/src/index.js to a dynamic import() which is available in all CommonJS modules.

    at Object.<anonymous> (/homebridge/node_modules/homebridge-kumo/node_modules/fetch-timeout/src/index.js:6:18)

    at Object.<anonymous> (/homebridge/node_modules/homebridge-kumo/dist/kumo-api.js:7:41)

    at Object.<anonymous> (/homebridge/node_modules/homebridge-kumo/dist/platform.js:4:20)

    at Object.<anonymous> (/homebridge/node_modules/homebridge-kumo/dist/index.js:3:20)

    at Plugin.load (/usr/local/lib/node_modules/homebridge/lib/plugin.js:135:108)

    at PluginManager.initializeInstalledPlugins (/usr/local/lib/node_modules/homebridge/lib/pluginManager.js:64:30)

    at async Server.start (/usr/local/lib/node_modules/homebridge/lib/server.js:106:9)

[1/22/2022, 12:16:22 PM] ====================

 

From: FTI76 ***@***.***>
Reply-To: fjs21/homebridge-kumo ***@***.***>
Date: Saturday, January 22, 2022 at 15:03
To: fjs21/homebridge-kumo ***@***.***>
Cc: Hans Winkler ***@***.***>, Author ***@***.***>
Subject: Re: [fjs21/homebridge-kumo] Latest plugin update killed my Kumo access through Homebridge (Issue #55)

 

It killed mine also - homebridge-kumo v1.8.21

[1/22/2022, 2:59:25 PM] ---
[1/22/2022, 2:59:25 PM] ====================
[1/22/2022, 2:59:25 PM] ERROR LOADING PLUGIN homebridge-kumo:
[1/22/2022, 2:59:25 PM] Error [ERR_REQUIRE_ESM]: require() of ES Module /usr/lib/node_modules/homebridge-kumo/node_modules/node-fetch/src/index.js from /usr/lib/node_modules/homebridge-kumo/node_modules/fetch-timeout/src/index.js not supported.
Instead change the require of /usr/lib/node_modules/homebridge-kumo/node_modules/node-fetch/src/index.js in /usr/lib/node_modules/homebridge-kumo/node_modules/fetch-timeout/src/index.js to a dynamic import() which is available in all CommonJS modules.
at Object. (/usr/lib/node_modules/homebridge-kumo/node_modules/fetch-timeout/src/index.js:6:18)
at Object. (/usr/lib/node_modules/homebridge-kumo/dist/kumo-api.js:7:41)
at Object. (/usr/lib/node_modules/homebridge-kumo/dist/platform.js:4:20)
at Object. (/usr/lib/node_modules/homebridge-kumo/dist/index.js:3:20)
at Plugin.load (/usr/lib/node_modules/homebridge/lib/plugin.js:135:108)
at PluginManager.initializeInstalledPlugins (/usr/lib/node_modules/homebridge/lib/pluginManager.js:64:30)
at async Server.start (/usr/lib/node_modules/homebridge/lib/server.js:106:9)
[1/22/2022, 2:59:25 PM] ====================

**Comment by hansw1204** [comment]
Thanks for looking into this. I am running

 

 

On HB version 1.4.0.

 

Also, Mitsubishi recently updated their iOS KUMO app, don't know if that could do anything.
Up To Date

 

 

 

From: Fraser Sim ***@***.***>
Reply-To: fjs21/homebridge-kumo ***@***.***>
Date: Saturday, January 22, 2022 at 16:34
To: fjs21/homebridge-kumo ***@***.***>
Cc: Hans Winkler ***@***.***>, Author ***@***.***>
Subject: Re: [fjs21/homebridge-kumo] Latest plugin update killed my Kumo access through Homebridge (Issue #55)

 

Ok. I'm running Node.js Version 16.13.0, NPM 8.1.0, and Homebridge 1.4.0. Working fine here. I'll need to dig further.

**Comment by fjs21** [comment]
Please try v1.8.22 which should take care of it. The bump in the version number to node-fetch caused this bug (not sure why it didn't affect my build). It is working now with the latest version (v3) of node-fetch.

**Comment by FTI76** [comment]
Looks Good!   Thanks for taking care of this so quickly.

[1/23/2022, 8:42:05 AM] [homebridge-kumo] Loaded homebridge-kumo v1.8.22 child bridge successfully
[1/23/2022, 8:42:05 AM] Loaded 3 cached accessories from cachedAccessories.0EF2A5C67892.
[1/23/2022, 8:42:05 AM] [homebridge-kumo] Loading accessory from cache: Living Room
[1/23/2022, 8:42:05 AM] [homebridge-kumo] Loading accessory from cache: Den
[1/23/2022, 8:42:05 AM] [homebridge-kumo] Loading accessory from cache: Bedroom
[1/23/2022, 8:42:05 AM] Homebridge v1.4.0 (HAP v0.10.0) (homebridge-kumo) is running on port 50703.
[1/23/2022, 8:42:06 AM] [homebridge-kumo] Kumo API: Successfully connected to the Kumo API.
[1/23/2022, 8:42:06 AM] [homebridge-kumo] Found device. Serial: 1834P008xF. Label: Living Room
[1/23/2022, 8:42:06 AM] [homebridge-kumo] Found device. Serial: 1834P008xF. Label: Den
[1/23/2022, 8:42:06 AM] [homebridge-kumo] Found device. Serial: 1834P00x1F. Label: Bedroom
[1/23/2022, 8:42:06 AM] [homebridge-kumo] Number of devices found: 3
[1/23/2022, 8:42:06 AM] [homebridge-kumo] Completed login.
[1/23/2022, 8:42:06 AM] [homebridge-kumo] Restoring existing accessory from cache: Living Room
[1/23/2022, 8:42:06 AM] [homebridge-kumo] Using Kumo Cloud API for device control
[1/23/2022, 8:42:07 AM] [homebridge-kumo] Initializing "Living Room" as ductless unit.
[1/23/2022, 8:42:07 AM] [homebridge-kumo] Restoring existing accessory from cache: Den
[1/23/2022, 8:42:07 AM] [homebridge-kumo] Using Kumo Cloud API for device control
[1/23/2022, 8:42:07 AM] [homebridge-kumo] Initializing "Den" as ductless unit.
[1/23/2022, 8:42:07 AM] [homebridge-kumo] Restoring existing accessory from cache: Bedroom
[1/23/2022, 8:42:07 AM] [homebridge-kumo] Using Kumo Cloud API for device control
[1/23/2022, 8:42:07 AM] [homebridge-kumo] Initializing "Bedroom" as ductless unit.

**Comment by hansw1204** [comment]
Thank you very much for fixing this so quickly.

 

Working here again, too with 1.8.22

 

I did find this in the logs

 

[1/23/2022, 11:38:34 AM] [homebridge-kumo] Dining Room (PowerSwitch): set Active to true.

[1/23/2022, 11:38:34 AM] [homebridge-kumo] Dining Room (Heater/Cooler): set Active from 0 to 1

[1/23/2022, 11:38:34 AM] [homebridge-kumo] Dining Room (Fan): set Swing to 0.

[1/23/2022, 11:38:36 AM] [homebridge-kumo] queryDevice_Direct error: Time out on local IP connection..

[1/23/2022, 11:38:36 AM] [homebridge-kumo] Kumo API: Failed to send command directly to device (Serial: 9X34P008S100090F).

 

Looks like an automation was trying to run but failed. I’m sure this is unrelated to the previous issue but I thought I might mention it. Should I turn Direct Access off?

 

 

From: FTI76 ***@***.***>
Reply-To: fjs21/homebridge-kumo ***@***.***>
Date: Sunday, January 23, 2022 at 08:44
To: fjs21/homebridge-kumo ***@***.***>
Cc: Hans Winkler ***@***.***>, Author ***@***.***>
Subject: Re: [fjs21/homebridge-kumo] Latest plugin update killed my Kumo access through Homebridge (Issue #55)

 

Looks Good! Thanks for taking care of this so quickly.

[1/23/2022, 8:42:05 AM] [homebridge-kumo] Loaded homebridge-kumo v1.8.22 child bridge successfully
[1/23/2022, 8:42:05 AM] Loaded 3 cached accessories from cachedAccessories.0EF2A5C67892.
[1/23/2022, 8:42:05 AM] [homebridge-kumo] Loading accessory from cache: Living Room
[1/23/2022, 8:42:05 AM] [homebridge-kumo] Loading accessory from cache: Den
[1/23/2022, 8:42:05 AM] [homebridge-kumo] Loading accessory from cache: Bedroom
[1/23/2022, 8:42:05 AM] Homebridge v1.4.0 (HAP v0.10.0) (homebridge-kumo) is running on port 50703.
[1/23/2022, 8:42:06 AM] [homebridge-kumo] Kumo API: Successfully connected to the Kumo API.
[1/23/2022, 8:42:06 AM] [homebridge-kumo] Found device. Serial: 1834P008xF. Label: Living Room
[1/23/2022, 8:42:06 AM] [homebridge-kumo] Found device. Serial: 1834P008xF. Label: Den
[1/23/2022, 8:42:06 AM] [homebridge-kumo] Found device. Serial: 1834P00x1F. Label: Bedroom
[1/23/2022, 8:42:06 AM] [homebridge-kumo] Number of devices found: 3
[1/23/2022, 8:42:06 AM] [homebridge-kumo] Completed login.
[1/23/2022, 8:42:06 AM] [homebridge-kumo] Restoring existing accessory from cache: Living Room
[1/23/2022, 8:42:06 AM] [homebridge-kumo] Using Kumo Cloud API for device control
[1/23/2022, 8:42:07 AM] [homebridge-kumo] Initializing "Living Room" as ductless unit.
[1/23/2022, 8:42:07 AM] [homebridge-kumo] Restoring existing accessory from cache: Den
[1/23/2022, 8:42:07 AM] [homebridge-kumo] Using Kumo Cloud API for device control
[1/23/2022, 8:42:07 AM] [homebridge-kumo] Initializing "Den" as ductless unit.
[1/23/2022, 8:42:07 AM] [homebridge-kumo] Restoring existing accessory from cache: Bedroom
[1/23/2022, 8:42:07 AM] [homebridge-kumo] Using Kumo Cloud API for device control
[1/23/2022, 8:42:07 AM] [homebridge-kumo] Initializing "Bedroom" as ductless unit.

**Comment by FTI76** [comment]
I am seeing similar errors but my automations are running not sure if it’s just defaulting to cloud API.

“It's such a fine line between stupid, and clever.” - David St. Hubbins

**Comment by hansw1204** [comment]
I checked and the appliance was already running, so the error may be generated by the fact that the appliance didn't turn on because it was already on.

 

From: FTI76 ***@***.***>
Reply-To: fjs21/homebridge-kumo ***@***.***>
Date: Sunday, January 23, 2022 at 11:52
To: fjs21/homebridge-kumo ***@***.***>
Cc: Hans Winkler ***@***.***>, Author ***@***.***>
Subject: Re: [fjs21/homebridge-kumo] Latest plugin update killed my Kumo access through Homebridge (Issue #55)

 

I am seeing similar errors but my automations are running not sure if it’s just defaulting to cloud API.

“It's such a fine line between stupid, and clever.” - David St. Hubbins

**Comment by FTI76** [comment]
I checked and the appliance was already running, so the error may be generated by the fact that the appliance didn't turn on because it was already on.

Mine are running today as well - Good call.   

Maybe I will add some logic if they are already powered on not to run.

**Comment by hansw1204** [comment]
Thank you, I don't think it’s critical, though.

 

 

From: FTI76 ***@***.***>
Reply-To: fjs21/homebridge-kumo ***@***.***>
Date: Sunday, January 23, 2022 at 13:53
To: fjs21/homebridge-kumo ***@***.***>
Cc: Hans Winkler ***@***.***>, Author ***@***.***>
Subject: Re: [fjs21/homebridge-kumo] Latest plugin update killed my Kumo access through Homebridge (Issue #55)

 

I checked and the appliance was already running, so the error may be generated by the fact that the appliance didn't turn on because it was already on.

Mine are running today as well - Good call.

Maybe I will add some logic if they are already powered on not to run.
