### ISSUE TITLE
New Error messages in log

### ISSUE THREAD

**Issue by hansw1204** [fjs21/homebridge-kumo#85]
[4/15/2023, 11:48:25 AM] [homebridge-kumo] This plugin generated a warning from the characteristic 'Cooling Threshold Temperature': characteristic was supplied illegal value: null! Home App will reject null for Apple defined characteristics. See https://homebridge.io/w/JtMGR for more info.
[4/15/2023, 11:48:25 AM] [homebridge-kumo] This plugin generated a warning from the characteristic 'Cooling Threshold Temperature': characteristic was supplied illegal value: null! Home App will reject null for Apple defined characteristics. See https://homebridge.io/w/JtMGR for more info.

This started happening recently, possibly related to Homekit new architecture upgrade

**Comment by hansw1204** [comment]
EDIT: Detailed log entry after turning on Debug mode
[4/15/2023, 12:19:57 PM] [homebridge-kumo] Found sensor.uuid: 6b730ad0a95f020000000000c73470d3
[4/15/2023, 12:19:57 PM] [homebridge-kumo] This plugin generated a warning from the characteristic 'Cooling Threshold Temperature': characteristic was supplied illegal value: null! Home App will reject null for Apple defined characteristics. See https://homebridge.io/w/JtMGR for more info.
[4/15/2023, 12:19:57 PM] [homebridge-kumo] Error: 
    at CoolingThresholdTemperature.Characteristic.characteristicWarning (/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:3011:105)
    at CoolingThresholdTemperature.Characteristic.validateUserInput (/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2862:14)
    at CoolingThresholdTemperature.Characteristic.updateValue (/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2328:20)
    at HeaterCooler.Service.updateCharacteristic (/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Service.ts:795:35)
    at KumoPlatformAccessory_ductless.updateTargetHeaterCoolingThresholdTemperature (/homebridge/node_modules/homebridge-kumo/src/ductless.ts:455:23)
    at KumoPlatformAccessory_ductless.updateAccessoryCharacteristics (/homebridge/node_modules/homebridge-kumo/src/ductless.ts:285:10)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)

**Comment by burtherman** [comment]
Yes seeing similar:

> This plugin generated a warning from the characteristic 'Heating Threshold Temperature': characteristic was supplied illegal value: null!

**Comment by Adelgiorno92** [comment]
Same errors on my end as well.
